
trigger:
- main


pool:
  vmImage: 'ubuntu-latest'

steps:

- script: echo "Pipeline is starting..."
  displayName: 'Start Message'


- script: |
    npm install
    npm run build
  displayName: 'Build Project'
